### ISSUE TITLE
Git version still using "Acme"; Style Update

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#39]
See HTML cover page:
<img width="681" alt="Screen Shot 2020-03-19 at 2 01 21 PM" src="https://user-images.githubusercontent.com/11865/77036488-3de67a80-69ea-11ea-9ec1-8910195bb8eb.png">

**Comment by ronaldtse** [comment]
ALL "Acme" text must be fixed.

**Comment by opoudjis** [comment]
Fixed, but now undertaking style update.

**Comment by opoudjis** [comment]
Things that need to be addressed for Ribose:

* What are the document types?
* What are the identifier prefixes corresponding to the document types?
* What are the possible values substituting "Ribose Asia Limited"? These are presumably the publisher?
* Do all documents have a recipient? ("Delivered to:") Is the recipient only ever specified as an email address?

**Comment by ronaldtse** [comment]
Fixed. Thanks! Answers will go into next issue.

**Comment by opoudjis** [comment]
The most unfortunate redaction of the sample pic forces me to document here the changes made.

* add personal authors to front page
* make Word fonts configurable
* add recipient of document as a field
* override document type in header to RR (for now, pending #41)
* override publisher in header to Ribose Asia Limited (for now, pending #41)
* change logo from SVG to PNG
* change almost all font sizes in Word to 12 pt
* change Word page margins
* move copyright notice after table of contents
* updates to Word cover page
* restyle annex headings
* add MMMddYYYY formatted date for revision date
