### ISSUE TITLE
Font changes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#40]
Let's reset the styling to ISO and tweak from there.

Font family changes:

* Arial -> Source Sans Pro
* Courier New -> Source Code Pro

Normal text / biblio: font size 12
Note type text: font size 11
Examples: don't bold

Header/footer margin adjustments

List paragraph should have more margin for separation (I un-ticked the "no spacing between text of the same type")

**Comment by opoudjis** [comment]
I've proceeded with this work under https://github.com/metanorma/metanorma-rsd/issues/39 before noticing this, and have substantially done it, though without referring to ISO as default.

As I have done all the tasks enumerated, I am closing this ticket.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
