### ISSUE TITLE
Clause numbers should follow ISO style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#42]
* Reference to clauses should be "Clause X", "X.Y.Z"
* Clause numbering should not be "X.Y.Z." but just "X.Y.Z" (no period at the end)

**Comment by opoudjis** [comment]
More hammering of nails into any idea that this should be a config only gem.

**Comment by ronaldtse** [comment]
It sounds like the other way round: the more this gem should be inherited from ISO.
