### ISSUE TITLE
Allow "Executive Summary" as clause before Introduction

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#43]
Just like NIST?

**Comment by opoudjis** [comment]
Hopefully that's already supported by `[.preface]`

However, by making coding demands like this, you are now making RSD no longer a pure config gem. Which is highly regrettable.

**Comment by opoudjis** [comment]
Any section with title "Executive Summary" will be moved to the preface, before the introduction, and will be tagged as `<executivesummary>`.

I will consider genericising executivesummary as a preface section, but unless that is done, RSD is no longer on the roadmap to be a config-only gem.
