### ISSUE TITLE
URGENT: XML file when directly passed to Metanorma displays error message

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#55]
```
mkdir -p documents/
nil versions are discouraged and will be deprecated in Rubygems 4
[metanorma] Error: Please specify a standard type: [:standoc, :iso, :iec, :ietf, :gb, :csd, :csa, :m3d, :generic, :un, :nist, :ogc, :itu, :rsd].
```

This error is due to this code in https://github.com/metanorma/metanorma/blob/2280105761080e82e2334da53e80d7b5950255b6/lib/metanorma/compile.rb#L31-L39

metanorma-rsd here registers its root tag as `generic-standard`, which doesn't match `red-standard`.

Debug code:
```ruby
    def xml_options_extract(file)
      xml = Nokogiri::XML(file)
      if xml.root
        puts "xml root is #{xml.root.name}"
        @registry.root_tags.each do |k, v|
          puts "k(#{k}), v(#{v})"
          return { type: k }  if v == xml.root.name
        end
      end
      {}
    end
```

Debug messages:
```
xml root is rsd-standard
k(standoc), v(standard-document)
k(iso), v(iso-standard)
k(iec), v(iec-standard)
k(ietf), v(ietf-standard)
k(gb), v(gb-standard)
k(csd), v(csd-standard)
k(csa), v(csa-standard)
k(m3d), v(m3d-standard)
k(generic), v(generic-standard)
k(un), v(un-standard)
k(nist), v(nist-standard)
k(ogc), v(ogc-standard)
k(itu), v(itu-standard)
k(rsd), v(generic-standard) <===!!!!
```

**Comment by w00lf** [comment]
> ```
> mkdir -p documents/
> nil versions are discouraged and will be deprecated in Rubygems 4
> [metanorma] Error: Please specify a standard type: [:standoc, :iso, :iec, :ietf, :gb, :csd, :csa, :m3d, :generic, :un, :nist, :ogc, :itu, :rsd].
> ```
> 
> This error is due to this code in https://github.com/metanorma/metanorma/blob/2280105761080e82e2334da53e80d7b5950255b6/lib/metanorma/compile.rb#L31-L39
> 
> metanorma-rsd here registers its root tag as `generic-standard`, which doesn't match `red-standard`.
> 
> Debug code:
> 
> ```ruby
>     def xml_options_extract(file)
>       xml = Nokogiri::XML(file)
>       if xml.root
>         puts "xml root is #{xml.root.name}"
>         @registry.root_tags.each do |k, v|
>           puts "k(#{k}), v(#{v})"
>           return { type: k }  if v == xml.root.name
>         end
>       end
>       {}
>     end
> ```
> 
> Debug messages:
> 
> ```
> xml root is rsd-standard
> k(standoc), v(standard-document)
> k(iso), v(iso-standard)
> k(iec), v(iec-standard)
> k(ietf), v(ietf-standard)
> k(gb), v(gb-standard)
> k(csd), v(csd-standard)
> k(csa), v(csa-standard)
> k(m3d), v(m3d-standard)
> k(generic), v(generic-standard)
> k(un), v(un-standard)
> k(nist), v(nist-standard)
> k(ogc), v(ogc-standard)
> k(itu), v(itu-standard)
> k(rsd), v(generic-standard) <===!!!!
> ```

@ronaldtse  As it turns out Metanorma::Registry depends on flavor Conevrter`s XML_ROOT_TAG constant: https://github.com/metanorma/metanorma/blob/2280105761080e82e2334da53e80d7b5950255b6/lib/metanorma/registry.rb#L51

And Asciidoctor::Rsd::Converter missed that constants, i have also created PR in metnorma-vsd to tackle the same issue: metanorma/metanorma-vsd#20.

**Comment by ronaldtse** [comment]
Thanks! Can you also help make XML_ROOT_TAG a part of configuration YAML? I can see the YAML of both gems have xml_root_tag but they are somehow not working in this situation.

**Comment by w00lf** [comment]
> Thanks! Can you also help make XML_ROOT_TAG a part of configuration YAML? I can see the YAML of both gems have xml_root_tag but they are somehow not working in this situation.

It is part of configuration but in case of melanoma-rsd configuration changes is not merged yet. With metanorma-vsd i have set this constant from configuration.

**Comment by opoudjis** [comment]
I'm not accepting that PR, because XML_ROOT_TAG must be set from the YAML file if present, and it *is* present.

**Comment by opoudjis** [comment]
OK

I am in HELL, and I do not have the time to be being pulled off on wild goose chases, but this is not the solution. The solution is to make XML_ROOT_TAG a function instead of a constant, because that is the only way  I am going to get the RSD and VSD to overwrite the value inherited from generic FROM WITHIN GENERIC (as opposed to the hack of the PR, which would need to be repeated every flavour that inherits from generic).

**Comment by opoudjis** [comment]
````
k(standoc), v(standard-document)
k(iso), v(iso-standard)
k(iec), v(iec-standard)
k(ietf), v(ietf-standard)
k(gb), v(gb-standard)
k(csd), v(csd-standard)
k(csa), v(csa-standard)
k(m3d), v(m3d-standard)
k(generic), v(generic-standard)
k(un), v(un-standard)
k(nist), v(nist-standard)
k(ogc), v(ogc-standard)
k(itu), v(itu-standard)
k(rsd), v(rsd-standard)
````

**Comment by opoudjis** [comment]
Getting this to run before release will need metanorma-standoc, metanorma-generic, metanorma fetched from github

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by ronaldtse** [comment]
Feel free to close when merged.
