### ISSUE TITLE
Term sourced from Relaton unable to render source

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-rsd#58]
The first one is sourced from Relaton, the second from a manual reference.

<img width="716" alt="Screen Shot 2020-04-29 at 10 16 22 AM" src="https://user-images.githubusercontent.com/11865/80555304-7b372280-8a02-11ea-98d6-367a8eea04e1.png">

**Comment by opoudjis** [comment]
Provide original document, please; I am not convinced this isn't a relaton-iso 1.0.1 issue.

**Comment by ronaldtse** [comment]
@opoudjis my mistake. Crazy day. Sorry.
